#---------------------------------------------------------------#
#------------------------  Test Resources  ---------------------#
#---------------------------------------------------------------#

resources:
# Set app version seed
  - name: seed_version_app
    type: version
    versionTemplate:
      versionName: "1.0.0"

# App TEST env vars
  - name: test_params_app
    type: params
    versionTemplate:
      params:
        ENVIRONMENT: "TEST"
        PORT: 80

# REPO of BVT Automation scripts
  - name: bvt_repo
    type: gitRepo
    integration: "demo_github"
    versionTemplate:
      sourceName: "aye0aye/test"
      branch: master

# SIT env vars
  - name: bvt_params
    type: params
    versionTemplate:
      params:
        API_URL: "54.158.18.50:8080"
        API_TOKEN: "NA"

#---------------------------------------------------------------#
#---------------------------  Test Jobs  -----------------------#
#---------------------------------------------------------------#

jobs:
# Trigger TEST Release
  - name: release_beta_app
    type: release
    steps:
      - IN: manifest_app
      - IN: seed_version_app
      - TASK: managed
        bump: beta
    flags:
      - e2e_demo_app

# Deploy to TEST environment
  - name: deploy_test_app
    type: deploy
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: release_beta_app
        deployName: test_app
      - IN: test_params_app
        switch: off
      - IN: test_env_ecs
        switch: off
#      - IN: e2eshipdemo-alb-test
#        applyTo:
#          - manifest: manifest_app
#            image: ecr_img_app
#            port: 80
      - TASK: managed
    flags:
      - e2e_demo_app

# Run Build Verification Tests
  - name: auto_bvt
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: deploy_test_app
      - IN: bvt_repo
      - IN: bvt_params
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bvt_repo")
            - echo "Starting Testing Env setup"
            - npm install
            - multi="xunit=shippable/testresults/test.xml json=shippable/testresults/test.json" npm run-script test-core
            - echo "Completed Testing Env setup"
            - popd
    flags:
      - e2e_demo_app
