#---------------------------------------------------------------#
#------------------------  Test Resources  ---------------------#
#---------------------------------------------------------------#

resources:
# Set app version seed
  - name: seed_version_app
    type: version
    versionTemplate:
      versionName: "1.0.0"

# App TEST env vars
  - name: test_params_app
    type: params
    versionTemplate:
      params:
        ENVIRONMENT: "TEST"
        PORT: 80

# REPO of BVT Automation scripts
  - name: bvt_repo
    type: gitRepo
    integration: "demo_github"
    versionTemplate:
      sourceName: "aye0aye/test"
      branch: master

# SIT env vars
  - name: bvt_params
    type: params
    versionTemplate:
      params:
        API_URL: "54.158.18.50:8080"
        API_TOKEN: "NA"

########################### Backend Test Resources ##########################
# BE Container Options
  - name: test_be_options
    type: dockerOptions
    version:
      memory: 128
      portMappings:
        - "6379:6379/tcp"
      labels:
        app: "test_be"

# BE Internal load-balancer
  - name: test_be_lb
    type: loadBalancer
    integration: demo_gke
    pointer:
      sourceName: "test-be-lb"
      method: ClusterIP
      clusterName: "cluster"
      region: "us-west1-a"
    version:
      ports:
        - name: testport
          protocol: TCP
          port: 6379
      selector:
        app: "test_be"

############################ Frontend Test Resources ###################
# FE Container Options
  - name: test_fe_options
    type: dockerOptions
    version:
      memory: 128
      portMappings:
        - "80:80/tcp"
      labels:
        app: "test_fe"

# FE External load-balancer
  - name: test_fe_lb
    type: loadBalancer
    integration: demo_gke
    pointer:
      sourceName: "test-fe-lb"
      method: LoadBalancer
      clusterName: "cluster"
      region: "us-west1-a"
    version:
      ports:
        - name: testport
          protocol: TCP
          port: 80
      selector:
        app: "test_fe"

# FE Env Vars
  - name: test_fe_params
    type: params
    version:
      params:
        REDIS: "test-be-lb"

#---------------------------------------------------------------#
#---------------------------  Test Jobs  -----------------------#
#---------------------------------------------------------------#

jobs:

########################### Google Cloud Kubernetes Jobs ########################
# BE App Create Template
  - name: appBETemp
    type: manifest
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: dh_img_app_be
      - IN: test_be_options
      - TASK: managed

# FE App Create Template
  - name: appFETemp
    type: manifest
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: dh_img_app_fe
      - IN: test_fe_params
      - IN: test_fe_options
      - TASK: managed

# Test Env Deploy
  - name: deploy_gke_test_app
    type: deploy
    method: replace
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: appBETemp
      - IN: appFETemp
      - IN: gke_cluster
      - TASK: managed

########################### AWS ECS Jobs ########################
# Trigger TEST Release
  - name: release_beta_app
    type: release
    steps:
      - IN: manifest_app
      - IN: seed_version_app
      - TASK: managed
        bump: beta
    flags:
      - e2e_demo_app

# Deploy to TEST environment
  - name: deploy_test_app
    type: deploy
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: release_beta_app
        deployName: test_app
      - IN: test_params_app
        switch: off
      - IN: test_env_ecs
        switch: off
#      - IN: e2eshipdemo-alb-test
#        applyTo:
#          - manifest: manifest_app
#            image: ecr_img_app
#            port: 80
      - TASK: managed
    flags:
      - e2e_demo_app

# Run Build Verification Tests
  - name: auto_bvt
    type: runSh
    dependencyMode: strict
    triggerMode: parallel
    steps:
      - IN: deploy_test_app
      - IN: bvt_repo
      - IN: bvt_params
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "bvt_repo")
            - echo "Starting Testing Env setup"
            - npm install
            - multi="xunit=shippable/testresults/test.xml json=shippable/testresults/test.json" npm run-script test-core
            - echo "Completed Testing Env setup"
            - popd
    flags:
      - e2e_demo_app
