apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-fe-{{ .Values.environment }}
spec:
  replicas: {{ .Values.fe.replicaCount}}
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-fe-{{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-fe-{{ .Values.environment }}
        image: {{ .Values.fe.image.repo }}:{{ .Values.fe.image.tag }}
        ports:
        - containerPort: {{ .Values.fe.port }}
        resources:
          requests:
            cpu: {{ .Values.fe.resources.requests.cpu }}
          limits:
            cpu: {{ .Values.fe.resources.limits.cpu }}
        env:
        - name: REDIS
          value: {{ .Values.fe.image.repo }}:{{ .Values.fe.image.tag }}
