environment: ${ENVIRONMENT}

be:
  replicaCount: 1
  image:
    repo: ${BE_IMG}
    tag: ${BE_TAG}
  port: 6379

fe:
  replicaCount: 1
  image:
    repo: ${FE_IMG}
    tag: ${FE_TAG}
  resources:
    requests:
      cpu: 250m
    limits:
      cpu: 500m
  port: 80
