apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.environment }}
  name: {{ .Values.be.label }}
spec:
  ports:
  - port: {{ .Values.be.port }}
  selector:
    app: {{ .Values.be.label }}
