apiVersion: apps/v1
kind: Service
metadata:
#  namespace: {{ .Values.environment }}
  name: {{ .Values.fe.label }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.fe.port }}
  selector:
    app: {{ .Values.fe.label }}
